skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
subsol_program = "HmYLKgRmZDAUG1tDPJ5xf55ut664EioACQQSyBAbA8MB"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
